<?php View::content() ?>

 <div class="card">

<div class="card-body">
<h2 class="card-title">Bienvenido! </h2>
<h6 class="card-title">Por favor ingrese sus datos</h6>

<form action="login/verifica" method="post">

<div class="form-group">

<label for="">Nombre de Usuario:</label>
<input type="text" name="nombre" id="" class="form-control" placeholder="" aria-describedby="helpId">

</div>

<div class="form-group">

<label for="">Password:</label>
<input type="password" name="pass" id="" class="form-control" placeholder="" aria-describedby="helpId">

</div>

<input type="submit" value="Entrar">
</form>


</div>
</div>